# Use official Node.js image as a base
FROM node:22.0.0

# Set the working directory
WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . ./

# Expose the application port
EXPOSE 9000

# Run the application
CMD ["sh", "-c", "npm run start:dev"]
