services:
  # BFF Server Redis
  # ----------------------------------------------------------------------------------------------------
  bff_server_redis:
    image: redis:latest
    container_name: bff_server_redis
    ports:
      - "9100:6379"
    volumes:
      - bff_server_redis_data:/data
    networks:
      - venomous_apps_network

networks:
  venomous_apps_network:
    driver: bridge

volumes:
  bff_server_redis_data:
